Repository Doom9527/aristotle-webservice, pull requests merged in 2024-09, with the labels that each got.

#4 为所有Controller、dto和vo添加swagger注解
  src/main/java/com/paiondata/aristotle/controller/GraphController.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/controller/UserController.java
  src/main/java/com/paiondata/aristotle/model/dto/BindNodeDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphAndNodeCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphUpdateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeRelationDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/RelationUpdateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/UserCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/UserUpdateDTO.java
  src/main/java/com/paiondata/aristotle/model/vo/GraphVO.java
  src/main/java/com/paiondata/aristotle/model/vo/UserVO.java
Labels: MERGEABLE

#19 The java check style plugin is turned off and some classes fail the check
  pom.xml
  src/main/java/com/paiondata/aristotle/common/exception/DeleteException.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphDeleteDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeDeleteDTO.java
  src/test/java/com/paiondata/aristotle/service/GraphNodeServiceSpec.java
  src/test/java/com/paiondata/aristotle/service/GraphServiceSpec.java
Labels: BUG

#24 Fix Docker Compose startup error - "Unable to connect to db:7687
  docker-compose.yml
Labels: BUG, MERGEABLE

#26 Publish documentation to dedicated domain 'aristotle-ws.com'
  .github/workflows/ci-cd.yml
  README.md
  docs/CNAME
  docs/docs/deployment.md
  docs/docusaurus.config.ts
Labels: DOCUMENTATION, NEED 1 REVIEW

#27 Return the metadata after the post request and update the corresponding test
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/controller/UserController.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphNodeDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeReturnDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/UserDTO.java
  src/main/java/com/paiondata/aristotle/repository/GraphNodeRepository.java
  src/main/java/com/paiondata/aristotle/service/GraphNodeService.java
  src/main/java/com/paiondata/aristotle/service/UserService.java
  src/main/java/com/paiondata/aristotle/service/impl/GraphNodeServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/UserServiceImpl.java
  src/test/groovy/com/paiondata/aristotle/AbstractITSpec.groovy
  src/test/java/com/paiondata/aristotle/service/GraphNodeServiceSpec.java
  src/test/java/com/paiondata/aristotle/service/UserServiceSpec.java
Labels: BUG, MERGEABLE
