Repository Doom9527/aristotle-webservice, pull requests merged in 2024-11, with the labels that each got.

#59 Using bfs to implement k-expand in java program instead of apoc plugin query in Neo4j
  docker-compose.yml
  src/main/java/com/paiondata/aristotle/aop/Neo4jTransactionAspect.java
  src/main/java/com/paiondata/aristotle/common/base/Constants.java
  src/main/java/com/paiondata/aristotle/common/base/Message.java
  src/main/java/com/paiondata/aristotle/common/util/NodeExtractor.java
  src/main/java/com/paiondata/aristotle/common/util/RelationShipExtractor.java
  src/main/java/com/paiondata/aristotle/config/BeanPostProcessorConfig.java
  src/main/java/com/paiondata/aristotle/config/Neo4jConfig.java
  src/main/java/com/paiondata/aristotle/controller/GraphController.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/controller/UserController.java
  src/main/java/com/paiondata/aristotle/exception/GlobalExceptionHandler.java
  src/main/java/com/paiondata/aristotle/mapper/GraphMapper.java
  src/main/java/com/paiondata/aristotle/mapper/NodeMapper.java
  src/main/java/com/paiondata/aristotle/mapper/impl/GraphMapperImpl.java
  src/main/java/com/paiondata/aristotle/mapper/impl/NodeMapperImpl.java
  src/main/java/com/paiondata/aristotle/repository/GraphRepository.java
  src/main/java/com/paiondata/aristotle/repository/NodeRepository.java
  src/main/java/com/paiondata/aristotle/repository/UserRepository.java
  src/main/java/com/paiondata/aristotle/service/CommonService.java
  src/main/java/com/paiondata/aristotle/service/GraphService.java
  src/main/java/com/paiondata/aristotle/service/NodeService.java
  src/main/java/com/paiondata/aristotle/service/UserService.java
  src/main/java/com/paiondata/aristotle/service/impl/CommonServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/GraphServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/NodeServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/UserServiceImpl.java
  src/test/java/com/paiondata/aristotle/common/base/TestConstants.java
  src/test/java/com/paiondata/aristotle/common/util/NodeExtractorTest.java
  src/test/java/com/paiondata/aristotle/common/util/RelationshipExtractorTest.java
  src/test/java/com/paiondata/aristotle/controller/NodeControllerIT.java
  src/test/java/com/paiondata/aristotle/mapper/NodeMapperTest.java
  src/test/java/com/paiondata/aristotle/service/NodeServiceTest.java
  src/test/resources/payload/create-a-node.json
  src/test/resources/payload/create-graph-nodes-to-expand.json
  src/test/resources/payload/create-graph-nodes-to-expend.json
Labels: CI/CD, MERGEABLE, REFACTORING

#64 Change the property nickName to username in User
  src/main/java/com/paiondata/aristotle/common/base/Message.java
  src/main/java/com/paiondata/aristotle/config/ConstraintInitializer.java
  src/main/java/com/paiondata/aristotle/model/dto/UserDTO.java
  src/main/java/com/paiondata/aristotle/model/entity/User.java
  src/main/java/com/paiondata/aristotle/model/vo/UserVO.java
  src/main/java/com/paiondata/aristotle/repository/UserRepository.java
  src/main/java/com/paiondata/aristotle/service/impl/UserServiceImpl.java
  src/test/java/com/paiondata/aristotle/common/base/TestConstants.java
  src/test/java/com/paiondata/aristotle/controller/GraphControllerIT.java
  src/test/java/com/paiondata/aristotle/controller/NodeControllerIT.java
  src/test/java/com/paiondata/aristotle/controller/UserControllerIT.java
  src/test/java/com/paiondata/aristotle/service/CommonServiceTest.java
  src/test/java/com/paiondata/aristotle/service/UserServiceTest.java
  src/test/resources/payload/create-update-user.json
Labels: MERGEABLE, REFACTORING

#65 Remove the bindNodes interface and delegate the functionality of creating relationships to createAndBindNode interface
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphAndNodeCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeCreateDTO.java
  src/main/java/com/paiondata/aristotle/service/NodeService.java
  src/main/java/com/paiondata/aristotle/service/impl/NodeServiceImpl.java
  src/test/java/com/paiondata/aristotle/controller/NodeControllerIT.java
  src/test/java/com/paiondata/aristotle/service/NodeServiceTest.java
  src/test/resources/payload/create-a-node.json
  src/test/resources/payload/create-graph-nodes-to-expand.json
  src/test/resources/payload/create-graph-nodes-to-valid.json
  src/test/resources/payload/create-graph-nodes.json
  src/test/resources/payload/create-node.json
  src/test/resources/payload/create-nodes-to-valid.json
  src/test/resources/payload/relate-node-to-valid.json
  src/test/resources/payload/relate-node.json
Labels: BUG, MERGEABLE, REFACTORING

#67 Initiate Cache documentation
  docs/docs/caching.mdx
  docs/docs/img/redis-caching.drawio
  docs/docs/img/redis-caching.png
Labels: DOCUMENTATION, MERGEABLE

#70 Add Troubleshooting section for deployment doc
  docs/docs/deployment.md
  docs/docs/img/redis-caching.drawio
  docs/docs/img/redis-caching.png
Labels: DOCUMENTATION, MERGEABLE

#71 Add 'Getting Started' Guide
  docs/docs/authorization.md
  docs/docs/deployment.md
  docs/docs/img/api-doc.png
  docs/docs/img/knife4j-creating-a-user.png
  docs/docs/img/neo4j-browser-new-user.png
  docs/docs/intro.md
  docs/docs/intro.mdx
Labels: DOCUMENTATION, MERGEABLE

#73 Move creating graph from NodeController to GraphController
  src/main/java/com/paiondata/aristotle/controller/GraphController.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/test/java/com/paiondata/aristotle/controller/AbstractIT.java
  src/test/java/com/paiondata/aristotle/controller/GraphControllerIT.java
  src/test/java/com/paiondata/aristotle/controller/NodeControllerIT.java
Labels: MERGEABLE, REFACTORING
