Repository Doom9527/aristotle-webservice, pull requests merged in 2024-10, with the labels that each got.

#28 Add javadoc plugin and add deployment steps in CI-CD
  .github/workflows/ci-cd.yml
  docs/docusaurus.config.ts
  pom.xml
Labels: DOCUMENTATION, MERGEABLE

#31 Support custom attributes on nodes and add Neo4j transaction AOP
  checkstyle-suppressions.xml
  pom.xml
  src/main/java/com/paiondata/aristotle/aop/Neo4jTransactionAspect.java
  src/main/java/com/paiondata/aristotle/common/annotion/Neo4jTransactional.java
  src/main/java/com/paiondata/aristotle/common/base/Constants.java
  src/main/java/com/paiondata/aristotle/common/base/Message.java
  src/main/java/com/paiondata/aristotle/common/exception/TransactionException.java
  src/main/java/com/paiondata/aristotle/common/util/Neo4jTransactionManager.java
  src/main/java/com/paiondata/aristotle/common/util/NodeExtractor.java
  src/main/java/com/paiondata/aristotle/common/util/TransactionManager.java
  src/main/java/com/paiondata/aristotle/config/Neo4jConfig.java
  src/main/java/com/paiondata/aristotle/controller/GraphController.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/controller/UserController.java
  src/main/java/com/paiondata/aristotle/mapper/GraphMapper.java
  src/main/java/com/paiondata/aristotle/mapper/NodeMapper.java
  src/main/java/com/paiondata/aristotle/mapper/UserMapper.java
  src/main/java/com/paiondata/aristotle/mapper/impl/GraphMapperImpl.java
  src/main/java/com/paiondata/aristotle/mapper/impl/NodeMapperImpl.java
  src/main/java/com/paiondata/aristotle/mapper/impl/UserMapperImpl.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeUpdateDTO.java
  src/main/java/com/paiondata/aristotle/model/entity/GraphNode.java
  src/main/java/com/paiondata/aristotle/model/vo/NodeVO.java
  src/main/java/com/paiondata/aristotle/repository/GraphRepository.java
  src/main/java/com/paiondata/aristotle/repository/NodeRepository.java
  src/main/java/com/paiondata/aristotle/service/CommonService.java
  src/main/java/com/paiondata/aristotle/service/GraphService.java
  src/main/java/com/paiondata/aristotle/service/Neo4jService.java
  src/main/java/com/paiondata/aristotle/service/NodeService.java
  src/main/java/com/paiondata/aristotle/service/UserService.java
  src/main/java/com/paiondata/aristotle/service/impl/CommonServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/GraphServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/Neo4jServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/NodeServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/UserServiceImpl.java
  src/test/groovy/com/paiondata/aristotle/AbstractITSpec.groovy
  src/test/java/com/paiondata/aristotle/service/CommonServiceSpec.java
  src/test/java/com/paiondata/aristotle/service/GraphServiceSpec.java
  src/test/java/com/paiondata/aristotle/service/NodeServiceSpec.java
  src/test/java/com/paiondata/aristotle/service/UserServiceSpec.java
  src/test/resources/payload/create-node.json
  src/test/resources/payload/relate-node.json
  src/test/resources/payload/update-graph.json
  src/test/resources/payload/update-node.json
Labels: MERGEABLE, NEW FEATURE, REFACTORING

#37 Master CI/CD should trigger an acceptance tests run
  .github/workflows/ci-cd.yml
Labels: CI/CD, MERGEABLE

#45 Add documentation for filtering
  docs/docs/filtering.md
Labels: DOCUMENTATION, MERGEABLE

#44 【Ready for Review】Implement new landing page UI
  .gitignore
  docs/docusaurus.config.ts
  docs/package.json
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/components/ParticleBackground.tsx
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/static/img/graph.ai
  docs/static/img/graph.svg
  docs/static/img/openapi-logo.svg
  docs/yarn.lock
Labels: DOCUMENTATION, MERGEABLE, NEED 1 REVIEW, REFACTORING

#39 Support filtering
  checkstyle-suppressions.xml
  src/main/java/com/paiondata/aristotle/aop/Neo4jTransactionAspect.java
  src/main/java/com/paiondata/aristotle/common/base/Constants.java
  src/main/java/com/paiondata/aristotle/common/base/Message.java
  src/main/java/com/paiondata/aristotle/common/base/ReturnCode.java
  src/main/java/com/paiondata/aristotle/common/util/NodeExtractor.java
  src/main/java/com/paiondata/aristotle/controller/GraphController.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/controller/UserController.java
  src/main/java/com/paiondata/aristotle/mapper/NodeMapper.java
  src/main/java/com/paiondata/aristotle/mapper/impl/GraphMapperImpl.java
  src/main/java/com/paiondata/aristotle/mapper/impl/NodeMapperImpl.java
  src/main/java/com/paiondata/aristotle/model/dto/BindNodeDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/FilterQueryGraphDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GetRelationDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphAndNodeCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphDeleteDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphNodeDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphUpdateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeDeleteDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeRelationDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeReturnDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/NodeUpdateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/RelationUpdateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/UserDTO.java
  src/main/java/com/paiondata/aristotle/model/vo/GraphVO.java
  src/main/java/com/paiondata/aristotle/model/vo/NodeVO.java
  src/main/java/com/paiondata/aristotle/model/vo/RelationVO.java
  src/main/java/com/paiondata/aristotle/service/GraphService.java
  src/main/java/com/paiondata/aristotle/service/NodeService.java
  src/main/java/com/paiondata/aristotle/service/impl/CommonServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/GraphServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/NodeServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/UserServiceImpl.java
  src/test/groovy/com/paiondata/aristotle/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/NodeMapperImplSpec.groovy
  src/test/java/com/paiondata/aristotle/base/TestConstants.java
  src/test/java/com/paiondata/aristotle/service/GraphServiceSpec.java
  src/test/java/com/paiondata/aristotle/service/NodeServiceSpec.java
  src/test/resources/payload/create-graph-nodes-to-valid.json
  src/test/resources/payload/create-graph-nodes.json
  src/test/resources/payload/create-nodes-to-valid.json
  src/test/resources/payload/delete-graph-to-valid.json
  src/test/resources/payload/get-graph-filter.json
  src/test/resources/payload/get-graph.json
  src/test/resources/payload/relate-node-to-valid.json
Labels: BUG, DOCUMENTATION, NEED CHANGES, NEW FEATURE

#47 Support searching in aristotle-ws.com
  .github/workflows/ci-cd.yml
  docs/docusaurus.config.ts
Labels: DOCUMENTATION, NEED 1 REVIEW

#52 Refactoring tests
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/test/groovy/com/paiondata/aristotle/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/DockerComposeITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/GraphControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/NodeControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/UserControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/mapper/NodeMapperImplSpec.groovy
  src/test/groovy/com/paiondata/aristotle/service/CommonServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/GraphServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/NodeServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/UserServiceSpec.java
Labels: CI/CD, MERGEABLE

#51 Support k-expand
  src/main/java/com/paiondata/aristotle/common/base/Constants.java
  src/main/java/com/paiondata/aristotle/common/base/Message.java
  src/main/java/com/paiondata/aristotle/common/exception/UserExistsException.java
  src/main/java/com/paiondata/aristotle/common/util/NodeExtractor.java
  src/main/java/com/paiondata/aristotle/config/ConstraintInitializer.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/controller/UserController.java
  src/main/java/com/paiondata/aristotle/mapper/GraphMapper.java
  src/main/java/com/paiondata/aristotle/mapper/NodeMapper.java
  src/main/java/com/paiondata/aristotle/mapper/impl/GraphMapperImpl.java
  src/main/java/com/paiondata/aristotle/mapper/impl/NodeMapperImpl.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphCreateDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/GraphDeleteDTO.java
  src/main/java/com/paiondata/aristotle/model/dto/UserDTO.java
  src/main/java/com/paiondata/aristotle/model/entity/User.java
  src/main/java/com/paiondata/aristotle/model/vo/UserVO.java
  src/main/java/com/paiondata/aristotle/repository/GraphRepository.java
  src/main/java/com/paiondata/aristotle/repository/UserRepository.java
  src/main/java/com/paiondata/aristotle/service/CommonService.java
  src/main/java/com/paiondata/aristotle/service/NodeService.java
  src/main/java/com/paiondata/aristotle/service/UserService.java
  src/main/java/com/paiondata/aristotle/service/impl/CommonServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/GraphServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/NodeServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/UserServiceImpl.java
  src/test/groovy/com/paiondata/aristotle/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/GraphControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/NodeControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/UserControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/service/CommonServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/GraphServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/NodeServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/UserServiceSpec.java
  src/test/java/com/paiondata/aristotle/base/TestConstants.java
  src/test/resources/payload/create-graph-nodes-to-expend.json
  src/test/resources/payload/create-graph-nodes-to-valid.json
  src/test/resources/payload/create-graph-nodes.json
  src/test/resources/payload/create-graph.json
  src/test/resources/payload/create-update-user.json
  src/test/resources/payload/delete-graph-to-valid.json
  src/test/resources/payload/delete-graph.json
Labels: MERGEABLE, NEW FEATURE, REFACTORING

#56 Remove the custom exception class and refactor the global exception handler
  src/main/java/com/paiondata/aristotle/aop/Neo4jTransactionAspect.java
  src/main/java/com/paiondata/aristotle/common/base/Message.java
  src/main/java/com/paiondata/aristotle/common/base/Result.java
  src/main/java/com/paiondata/aristotle/common/exception/BaseException.java
  src/main/java/com/paiondata/aristotle/common/exception/DeleteException.java
  src/main/java/com/paiondata/aristotle/common/exception/GraphExistsException.java
  src/main/java/com/paiondata/aristotle/common/exception/GraphNullException.java
  src/main/java/com/paiondata/aristotle/common/exception/NodeExistsException.java
  src/main/java/com/paiondata/aristotle/common/exception/NodeNullException.java
  src/main/java/com/paiondata/aristotle/common/exception/NodeRelationException.java
  src/main/java/com/paiondata/aristotle/common/exception/TemporaryKeyException.java
  src/main/java/com/paiondata/aristotle/common/exception/TransactionException.java
  src/main/java/com/paiondata/aristotle/common/exception/UserExistsException.java
  src/main/java/com/paiondata/aristotle/common/exception/UserNullException.java
  src/main/java/com/paiondata/aristotle/controller/NodeController.java
  src/main/java/com/paiondata/aristotle/exception/GlobalExceptionHandler.java
  src/main/java/com/paiondata/aristotle/model/dto/BindNodeDTO.java
  src/main/java/com/paiondata/aristotle/service/NodeService.java
  src/main/java/com/paiondata/aristotle/service/impl/CommonServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/GraphServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/NodeServiceImpl.java
  src/main/java/com/paiondata/aristotle/service/impl/UserServiceImpl.java
  src/test/groovy/com/paiondata/aristotle/controller/GraphControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/NodeControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/controller/UserControllerITSpec.groovy
  src/test/groovy/com/paiondata/aristotle/service/CommonServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/GraphServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/NodeServiceSpec.java
  src/test/groovy/com/paiondata/aristotle/service/UserServiceSpec.java
Labels: CI/CD, MERGEABLE, REFACTORING
